# Generated by Django 5.1.7 on 2026-03-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='sample_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('EMAIL', 'Email'), ('HTTP_FETCH', 'HTTP Fetch')], max_length=50),
        ),
    ]
