# Generated by Django 5.1.7 on 2026-03-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_action_sample_payload_alter_action_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
